<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link   href="<?php echo $this->baseUrl('visual/metro/css/metro.css') ?>" rel="stylesheet"/>
  <link   href="<?php echo $this->baseUrl('visual/metro/css/metro-responsive.css') ?>" rel="stylesheet"/>
  <link   href="<?php echo $this->baseUrl('visual/metro/css/metro-icons.css') ?>" rel="stylesheet"/>
  <script src="<?php echo $this->baseUrl('visual/jquery.min.js')?>"></script>
  <script src="<?php echo $this->baseUrl('file-upload/dropzone.js') ?>"></script>
  <script src="<?php echo $this->baseUrl('visual/metro/js/metro.js')?>"></script>
  <title>IMGBank</title>
</head>
<?php echo $this->headScript(); ?>
<body class="bg-gray">
  <!-- Fixed navbar -->
  <div class="app-bar bg-grayDarker" style="padding-left:200px;padding-right:200px">
    <div class="app-bar-element place-left bg-hover-black">
      <a href="<?php echo $this->baseUrl('index')?>"><img src="<?php echo $this->baseUrl('visual/logo.png')?>" style="height:50px"/></a>
    </div>

    <?php if(!empty($_SESSION['user'])){?>
      <div class="app-bar-element place-left bg-hover-grayDarker">
        <button class="button loading-cube lighten primary" onclick="showDialog('#dialog')">Upload</button>
      </div>
      <div class="app-bar-element place-right bg-hover-black">
        <a href="<?php echo $this->baseUrl('index/unset')?>" class="fg-white"><span class="mif-exit mif-2x"></span></a>
      </div>
      <div class="app-bar-element place-right bg-hover-black">
        <a href="<?php echo $this->baseUrl('perfil/perfil')?>" class="fg-white"><span class="mif-user mif-2x"></span></a>
      </div>
      <?php }else{?>
        <div class="app-bar-element place-right bg-hover-black">
          <a class="dropdown-toggle fg-white" href="#"><span class="mif-enter"></span>Entrar</a>
          <div class="app-bar-drop-container bg-white fg-dark place-right"
          data-role="dropdown" data-no-close="true">
          <div class="padding20">
            <form data-show-required-state="false" data-role="validator" action="<?php echo $this->baseUrl('index/logar')?>" method="post" id="login-form">
              <h4 class="text-light">Login</h4>
              <div class="input-control text">
                <span class="mif-user prepend-icon"></span>
                <input
                data-validate-func="required"
                placeholder="Usuario"
                type="text" name="user">
                <span class="input-state-error mif-warning"></span>
              </div>
              <div class="input-control text">
                <span class="mif-lock prepend-icon"></span>
                <input
                data-validate-func="required"
                placeholder="Senha"
                type="password" name="pass">
                <span class="input-state-error mif-warning"></span>
              </div>
              <label class="input-control checkbox small-check">
                <input type="checkbox">
                <span class="check"></span>
                <span class="caption">Me lembre</span>
              </label>
              <div class="form-actions">
                <input class="button" type="submit" value="Login">
                <button class="button link">Esqueci minha senha</button>
                <a href="<?php echo $this->baseUrl('perfil/cadastro')?>" class="button link">Não tem conta?</a>
              </div>
            </form>
          </div>
        </div>
      </div><?php } ?>
    </div>
    <div style="width: auto; height: auto; visibility: visible;" data-role="dialog" id="dialog" class="padding20 dialog" data-close-button="true" data-overlay="true" data-overlay-color="op-dark" data-overlay-click-close="true">
      <div class="flex-grid">
        <div class="row cells2">
          <div class="cell size2">
            <h4>Do seu computador</h4>
            <?php echo $this->baseUrl('perfil/upload'); ?>
            <form action="<?php echo $this->baseUrl('perfil/upload')?>">
              <div class="input-control file" data-role="input">
                <input type="file">
                <button class="button"><span class="mif-folder"></span></button>
              </div>
          </div>
          <div class="cell size6" style="margin-left:20px">
            <h4>Da internet:</h4>
            <div class="input-control" data-role="input">
              <input type="text" name="name" value="">
            </div>
          </div>
        </div>
      </div>
          <div class="grid">
            <div class="row">
              <div class="cell">
                <input type="submit" name="name" value="Enviar">
              </div>
            </div>
          </div>
        </form>
      <span class="dialog-close-button"></span></div>
      <script>
      function showDialog(id){
        var dialog = $(id).data('dialog');
        dialog.open();
      }
      </script>
      <div class="container"  style="margin-top: 60px;">
        <?php echo $this->layout()->content; ?>
      </div>
    </body>
    </html>
