<?php
    if($_SESSION){
        echo $_SESSION['mensagem'];
    }
?>
<div class="flex-grid">
    <div class="row flex-just-center">
        <div class="cell size6">
            <h4 class="fg-white">Compartilhe e salve seus momentos preferidos</h4>
        </div>
    </div>
</div>
<div class="grid index">
    <div class="row cells5">
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>
    </div>
    <div class="row cells5">
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>
        <div class="cell">
            <div class="image-container rounded">
                <img src="http://publicador.tvcultura.com.br/upload/tvcultura/programas/programa-imagem-som.jpg" style="height:150px" />
            </div>
        </div>

    </div>
</div>
<!-- TODO : Implementar Upload -->
